[build]
  command = "pnpm run build" # Replace with your build command
  publish = ".next" # Replace with your Next.js build output directory

[build.environment]
  NODE_VERSION = "18" # Replace with your preferred Node.js version

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Define your custom headers and redirects here as necessary
# [[redirects]]
#   from = "/old-page"
#   to = "/new-page"
#   status = 301
#
# [[headers]]
#   for = "/*.jpg"
#   [headers.values]
#     Cache-Control = "public, max-age=604800, immutable"

# Uncomment the following lines if you want to enable Netlify functions
# [build]
#   functions = "lambda"
#   command = "npm run build && npm run build:functions"